### PR TITLE
Feature/add sway specific tutorials

### PR DESCRIPTION
**Pull request by lipflip010**
While setting up regolith with sway/wayland I realized that the tutorials do not mention sway specifics/differences. This PR contains my solutions that I found for two tutorials. Let me know if I should adapt the formatting somehow! 

cc: @kgilmer

### CODE REVIEW

**Review by kgilmer — APPROVED** [review]
Fantastic, thank you @lipflip010

**Comment by kgilmer** [comment]
@SoumyaRanjanPatnaik any concerns?

**Review by SoumyaRanjanPatnaik — APPROVED** [review]
LGTM

**Comment by SoumyaRanjanPatnaik** [comment]
I think we should add a dedicated page for customising `i3status-rs` that links to the official i3status-rs documentation.

**Comment by SoumyaRanjanPatnaik** [comment]
While we're at it, we should also add docs for some of the other sway-related quirks e.g. setting environment variables, screen mirroring, screenshots, e.t.c.

**Comment by lipflip010** [comment]
Thanks for the feedback! :) Since both of you approved, is there a specific reason why it hasn't been merged yet? (I cannot do so as I'm lacking write-access)

**Comment by lipflip010** [comment]
> While we're at it, we should also add docs for some of the other sway-related quirks e.g. setting environment variables, screen mirroring, screenshots, e.t.c.

I agree, while setting up regolith with sway I realized quickly that most of the documentation is written specifically with i3 in mind. Which of course is not a dealbreaker, as sway is to a large degree a drop-in replacement for i3. But as you say, there *are* some quirks/differences to using sway.

Only later, I saw that sway support was only added with one of the latest releases of regolith. I was wondering then if regolith sway is still considered to be an alpha/beta version or if only the documentation is behind?

**Comment by lipflip010** [comment]
Also regarding linking the i3status-rust docs: I noticed that there were some "breaking changes" in i3status-rust that are not yet incoporated in regolith.

I noticed this when setting up a bluetooth block. In the current version used by regolith, one of the attributes for this block is called *format_disconnected* [1], but in the latest docs it's called *disconnected_format* [2].

[1] https://github.com/regolith-linux/i3status-rs_debian/blob/ubuntu/v0.22.0/src/blocks/bluetooth.rs#L242
[2] https://docs.rs/i3status-rs/latest/i3status_rs/blocks/bluetooth/index.html#:~:text=icon%20%24name%7B%20%24percentage%7C%7D%20%E2%80%9C-,disconnected_format,-A%20string%20to

**Comment by SoumyaRanjanPatnaik** [comment]
> Thanks for the feedback! :) Since both of you approved, is there a specific reason why it hasn't been merged yet? (I cannot do so as I'm lacking write-access)

@kgilmer do you think this can be merged? We can have a separate issue for documenting the other stuff.

> I was wondering then if regolith sway is still considered to be an alpha/beta version or if only the documentation is behind

The sway session is still a beta although I personally use it as a daily driver and think it should be good enough for daily use. The documentation is definitely behind is this is something to be worked on.

> I noticed this when setting up a bluetooth block. In the current version used by regolith, one of the attributes for this block is called format_disconnected [1], but in the latest docs it's called disconnected_format [2].
>
> [1] https://github.com/regolith-linux/i3status-rs_debian/blob/ubuntu/v0.22.0/src/blocks/bluetooth.rs#L242
> [2] https://docs.rs/i3status-rs/latest/i3status_rs/blocks/bluetooth/index.html#:~:text=icon%20%24name%7B%20%24percentage%7C%7D%20%E2%80%9C-,disconnected_format,-A%20string%20to

The link you shared points to an older branch of `i3status-rs_debian`. Please refer https://github.com/regolith-linux/i3status-rs_debian/tree/ubuntu/v0.32.1, which is mostly up to date with the latest release (v0.32.3).

**Comment by kgilmer** [comment]
> @kgilmer do you think this can be merged? We can have a separate issue for documenting the other stuff.
:+1:

**Comment by kgilmer** [comment]
> ...although I personally use it as a daily driver..

As do I at home.  I stick with x11 at work because I'm on an older version of Ubuntu.

**Comment by lipflip010** [comment]
Thanks! :)

**Comment by lipflip010** [comment]
@SoumyaRanjanPatnaik, thanks for the background information and the link for the correct branch 😊  I was trying to figure out which version was used, but did not quite find the correct information

**Pull request merged**
