### PR TITLE
docs: expand time-format.md howtos with simple example

### PR DESCRIPTION
**Pull request by thebetar**

### CODE REVIEW

**Comment by kgilmer** [comment]
Thanks @thebetar !

**Review by kgilmer — APPROVED** [review]
LGTM

**Comment by thebetar** [comment]
I would like to contribute more to this specific how to and others where I find things that are unclear to me as a beginner, can I make a future pull request with multiple additions?

**Comment by kgilmer** [comment]
> can I make a future pull request with multiple additions?

Absolutely!

**Pull request merged**
