### PR TITLE
Regolith 3.1 release info

### PR DESCRIPTION
**Pull request by kgilmer**
* Update landing page and install page info to say 3.1
* Remove no longer supported versions of Ubuntu from install directions
* Update 3.1 release notes with latest changes
* Clean up some old content that referred to installing Regolith 2.x

### CODE REVIEW

**Comment by kgilmer** [comment]
Related PR: https://github.com/regolith-linux/voulage/pull/28

**Review by SoumyaRanjanPatnaik — APPROVED** [review]
LGTM

**Comment by kgilmer** [comment]
Is this alright w/ you @SoumyaRanjanPatnaik ?  https://github.com/regolith-linux/regolith-desktop-website/pull/41/commits/5aae771d8e7195f4d3cf2310582ed79fa91374e4

**Comment by SoumyaRanjanPatnaik** [comment]
Yep. Sounds good to me.

**Pull request merged**
