### PR TITLE
Fix config path in a doc page

### PR DESCRIPTION
**Pull request by brvoisin**
I fixed the configuration directory path in the page "Customize i3 Configuration".

### CODE REVIEW

**Comment by mfisher87** [comment]
The diff for this PR is incorrect and I haven't been able to get GitHub to refresh it. The English docs were fixed last year, but the French translation still has this issue. I hoped changing the base branch and back would resolve, but doesn't seem like it. Would you update the branch on your fork from the upstream main branch to fix this?

**Comment by mfisher87** [comment]
This is expected behavior I'd never paid much attention to before. GitHub is using "three dot" comparison here, so this branch is being compared to the latest common ancestor. I think this looks good but @kgilmer may want the fork updated from upstream before merging so the diff is more "correct" when viewing the PR from GitHub UI.

**Review by mfisher87 — APPROVED** [review]

**Review by kgilmer — APPROVED** [review]
LGTM

**Comment by kgilmer** [comment]
Thank you @brvoisin !

**Pull request merged**
